In [2]:
import numpy as np

lending_co_TP = np.loadtxt('data/Lending-Company-Numeric-Data.csv', delimiter=',')

print(lending_co_TP)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [ 2000.    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


In [3]:
np.set_printoptions(suppress = True, linewidth = 150)

# suppress=True prevents small floating-point numbers from being displayed in scientific notation.

# linewidth=150 increases the number of characters per line before wrapping, 
# helping to display more of the array on a single line.

lending_co_TP = np.genfromtxt('data/Lending-Company-Numeric-Data.csv', delimiter=',')

print(lending_co_TP)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [ 2000.    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


In [4]:
filename = 'data/Lending-Company-Numeric-Data.csv'
lending_co_TP = np.genfromtxt(filename, 
                                delimiter=',',
                                dtype=str,
                                skip_header=1,
                                skip_footer=15,
                                usecols=(2, 3, 5))

print(lending_co_TP)


[['365' '3061' '15041']
 ['365' '2160' '15340']
 ['365' '3041' '15321']
 ...
 ['365' '2480' '15600']
 ['365' '3401' '16600']
 ['365' '3401' '20250']]


In [5]:
lending_co_TP = np.genfromtxt('data/Lending-Company-Numeric-Data.csv',
                              delimiter=',',
                              dtype=str,
                              skip_header=1,
                              skip_footer=15,
                              usecols=(2, 3 ,5),
                              comments='#',
                              converters=None,
                              missing_values='NaN',
                              deletechars='()*+,-./:;<=>?@[\\]^{|}~',
                              filling_values='_')

# instad for stripping, can be used autrostrip= in genfromtxt

stripped = np.char.strip(lending_co_TP)
print(stripped)

[['365' '3061' '15041']
 ['365' '2160' '15340']
 ['365' '3041' '15321']
 ...
 ['365' '2480' '15600']
 ['365' '3401' '16600']
 ['365' '3401' '20250']]


In [6]:
lending_co_TP = np.genfromtxt('data/Lending-company.csv',
                              delimiter=',',
                              dtype=str,
                              skip_header=1)

print(lending_co_TP)

[['1' 'LoanID_1' 'Product B' ... '4166' '14621' 'Active']
 ['2' 'LoanID_2' 'Product D' ... '4096' '16041' 'Active']
 ['3' 'LoanID_3' 'Product B' ... '3205' '16340' '']
 ...
 ['1041' 'LoanID_1041' 'Product A' ... '5143' '16617' 'Finished Payment']
 ['1042' 'LoanID_1042' 'Product B' ... '3462' '15617' 'Finished Payment']
 ['1043' 'LoanID_1043' 'Product A' ... '4743' '16617' 'Finished Payment']]


In [7]:
lending_co_TP = np.genfromtxt('data/Lending-company.csv',
                              delimiter=',',
                              skip_footer=1,
                              usecols=(0, -1),
                              dtype=np.int32)
                            
print(lending_co_TP)

[[  -1   -1]
 [   1   -1]
 [   2   -1]
 ...
 [1040   -1]
 [1041   -1]
 [1042   -1]]


In [8]:
lending_co_TP = np.genfromtxt("data/Lending-Company-Numeric-Data.csv", 
                              delimiter = ',',
                              dtype = str,
                              skip_header = 1, 
                              skip_footer = 15,
                              usecols = (1,2,4),
                              comments = '#',
                              converters = None,
                              missing_values = None,
                              excludelist = None,
                              deletechars = " !#$%&'()*+,-./:;<=>?@[\\]^{|}~",
                              replace_space = '_',
                              autostrip = True
                             )
print(lending_co_TP)

[['40' '365' '4171']
 ['40' '365' '3280']
 ['40' '365' '4241']
 ...
 ['40' '365' '3600']
 ['40' '365' '4601']
 ['50' '365' '4801']]
